<div class="perfilPainel">
  <div class="row mt-2 mb-2">
    <div class="col mb-2">
      <span class="perfilPainelNome"><?=$this->view->infoUsuario['nome']?></span>
    </div>
  </div>
  <div class="row mb-2">
    <div class="col">
      <span class="perfilPainelItem">Tweets</span><br />
      <span class="perfilPainelItemValor"><?=$this->view->infoUsuario['total_tweets']?></span>
    </div>
    <div class="col">
      <span class="perfilPainelItem">Seguindo</span><br />
      <span class="perfilPainelItemValor"><?=$this->view->infoUsuario['total_seguindo']?></span>
    </div>
    <div class="col">
      <span class="perfilPainelItem">Seguidores</span><br />
      <span class="perfilPainelItemValor"><?=$this->view->infoUsuario['total_seguidores']?></span>
    </div>
  </div>
</div>